www/components/Logo.tsx
www/pages/[id].tsx

Fix Forward/backward buttons break on small screens

---

.github/workflows/ci.yml
_tools/check_valid_data.ts

This PR's will fail CI until https://github.com/denoland/denobyexample/pull/35 lands. We should probably merge both at the same time.

feat: ci to check valid data

---

data/os-signals.ts
toc.js

This adds an example for listening to OS signals, with both addition and removal.

Add OS signals example

---

data/tcp-listener.ts
toc.js

tcp listener

---

data/hex-base64-encoding.ts
toc.js

it looks like changing the branch name closed the other PR. Pinging @LeoDog896 and @kt3k to PTAL.

feat: hex and base64 encoding

---

data/tcp-connector.ts
toc.js

#5 tcp connector

---

data/permissions.ts

Sync permissions landed after this example page was written but it's probably worth mentioning them here.

chore: update permissions example to include sync

---

data/hashing.ts
toc.js

This is probably an important example to have. I wish this existed as a resource when I was trying to optimize file hashing over at tea.

feat: hashing example

---

data/checking-file-existence.ts
toc.js

95% of this example is quite literally text, but I think this makes sense given the circumstances.

feat: add file existence check example

---

data/path-operations.ts
toc.js

Just wanted to move the PR forward. Added @TeoDev1611 as a coauthor. Thanks for the initial work!
I don't think a dedicated example to deleting files is necessary. At most, I would maybe modify another example to add deleting files.
Supersedes #17

feat: path operations

---

data/subprocesses-output.ts
data/subprocesses-spawn.ts
toc.ts
www/import_map.json
www/utils/example.ts

I also went ahead and rewrote a small part of the last subprocess example and bumped the std version.

feat: subprocess spawning

---

data/reading-files.ts
data/streaming-files.ts
data/writing-files.ts
toc.ts

I also took the liberty to update some outdated references to `Deno.File`.

feat: streaming files

---

data/parsing-serializing-csv.ts
toc.ts

Probably the hardest of the parsing / serializing examples to write. CSV is really not standardized.

feat: CSV example

---

www/routes/[id]/index.tsx

feat: edit button

---

data/http-requests.ts

fix: http-requests example

---

data/deleting-files.ts
data/hashing.ts
data/importing-json.ts
data/kv.ts
data/permissions.ts
data/subprocesses-spawn.ts
data/udp-connector.ts
data/websocket.ts
data/writing-files.ts
data/writing-tests.ts
www/deno.json
www/utils/example.ts

Closes #94. Changed examples as needed to remove errors.

fix: modernize the examples

---

data/importing-json.ts

I think this was used at one point but no longer is?

chore: remove unnecessary permission

---

data/mongo.ts
data/subprocesses-output.ts
toc.ts

docs: adds mongodb example

---

data/ulid.ts
deno.json
toc.ts
utils/example.ts

feat: add ULID example

---

.gitignore
data/byte-manipulation.ts
data/command-line-arguments.ts
data/dependency-management.ts
data/hashing.ts
data/hex-base64-encoding.ts
data/http-server-files.ts
data/parsing-serializing-csv.ts
data/parsing-serializing-toml.ts
data/parsing-serializing-yaml.ts
data/path-operations.ts
data/piping-streams.ts
data/ulid.ts
data/uuids.ts
data/walking-directories.ts
data/watching-files.ts
data/writing-tests.ts
deno.json
fresh.gen.ts
routes/_app.tsx

Closes #124. Right now the versions aren't pinned. This probably won't be a big deal with the upcoming stabilization of std, but something to note.

feat: update examples to use jsr + update fresh
